# Generated by Django 3.0.3 on 2020-03-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
