# Generated by Django 3.0.3 on 2020-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daka', '0004_auto_20200303_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.TextField(max_length=30),
        ),
    ]
