# Generated by Django 3.0.3 on 2020-03-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daka', '0006_auto_20200304_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='user',
        ),
    ]
