# Generated by Django 3.0.3 on 2020-03-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daka', '0007_auto_20200304_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user',
            new_name='username',
        ),
    ]
