# Generated by Django 3.0.3 on 2020-03-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daka', '0008_auto_20200304_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='tel',
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=111, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
