# Generated by Django 3.0.3 on 2020-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daka', '0009_auto_20200304_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('number', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
